name: Update upstream
on:
#  schedule:
#    - cron: '0 15 * * *' # Once a day at 5pm GMT+2
  workflow_dispatch: # on button click

jobs:
  upstream:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Git Repository
        uses: actions/checkout@v2
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Cache Gradle
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties', '**/gradle.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Set up JDK
        uses: actions/setup-java@v2.3.0
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Configure Git User Details
        run: git config --global user.email "actions@github.com" && git config --global user.name "Github Actions"
      - name: Update upstream commit no
        run: .github/generate_gradle_properties.py > gradle.properties
      - name: Apply Patches
        run: ./gradlew applyPatches --stacktrace
      - name: Build
        run: ./gradlew createReobfPaperclipJar --stacktrace
      - name: Set outputs
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      - name: Check outputs
        run: echo ${{ steps.vars.outputs.sha_short }}
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.vars.outputs.sha_short }}
          release_name: "LinearPaper 1.19.4"
          body: |
            LinearPaper updated upstream
          draft: false
          prerelease: false
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: Update Upstream
          branch: update-upstream
          delete-branch: true
          title: 'Update Upstream'
          body: ''
